name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
